apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: kgv-dev

resources:
- ../../base

commonLabels:
  environment: development
  app.kubernetes.io/instance: kgv-dev

images:
- name: acrkgvprod.azurecr.io/kgv-api
  newTag: dev-latest
- name: acrkgvprod.azurecr.io/kgv-web
  newTag: dev-latest

replicas:
- name: kgv-api
  count: 1
- name: kgv-web
  count: 1
- name: postgres
  count: 1
- name: redis
  count: 1

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Development
  - NODE_ENV=development
  - LOG_LEVEL=Debug
  - ENABLE_SWAGGER=true
  - ENABLE_DETAILED_ERRORS=true
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
- patches/namespace.yaml
- patches/ingress.yaml
- patches/resources.yaml

patches:
- target:
    kind: HorizontalPodAutoscaler
    name: kgv-api-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
- target:
    kind: HorizontalPodAutoscaler
    name: kgv-web-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
- target:
    kind: PersistentVolumeClaim
    name: postgres-data
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 20Gi
- target:
    kind: PersistentVolumeClaim
    name: redis-data
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 5Gi