# Kustomization for base Kubernetes resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kgv-system

commonLabels:
  app.kubernetes.io/part-of: kgv-migration
  app.kubernetes.io/managed-by: kustomize

resources:
  # Namespace
  - namespace.yaml
  
  # Service Accounts and RBAC
  - service-accounts.yaml
  - rbac.yaml
  
  # ConfigMaps and Secrets
  - configmap-app.yaml
  - postgres-init-configmap.yaml
  - secret-app.yaml
  
  # PostgreSQL Database
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  
  # Redis Cache
  - redis-pvc.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  
  # API Application
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  
  # Web Application
  - web-deployment.yaml
  - web-service.yaml
  - web-hpa.yaml
  
  # Ingress
  - ingress.yaml
  
  # Network Policies
  - network-policies.yaml
  
  # Pod Disruption Budgets
  - pdb.yaml

images:
  - name: acrkgvprod.azurecr.io/kgv-api
    newTag: latest
  - name: acrkgvprod.azurecr.io/kgv-web
    newTag: latest

replicas:
  - name: kgv-api
    count: 2
  - name: kgv-web
    count: 2
  - name: postgres
    count: 1
  - name: redis
    count: 1