# Kustomization for base Kubernetes resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kgv-system

commonLabels:
  app.kubernetes.io/part-of: kgv-migration
  app.kubernetes.io/managed-by: kustomize

resources:
  # Namespace
  - namespace.yaml
  
  # ConfigMaps and Secrets
  - configmap-app.yaml
  - secret-app.yaml
  
  # Database
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  
  # Redis
  - redis-deployment.yaml
  - redis-service.yaml
  
  # API Application
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  
  # Web Application
  - web-deployment.yaml
  - web-service.yaml
  - web-hpa.yaml
  
  # Ingress
  - ingress.yaml
  
  # Network Policies
  - network-policies.yaml
  
  # Service Accounts and RBAC
  - service-accounts.yaml
  - rbac.yaml
  
  # Pod Disruption Budgets
  - pdb.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOG_LEVEL=Information
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: app-secrets
    type: Opaque
    literals:
      - JWT_SECRET=replaceme
      - DB_PASSWORD=replaceme
      - REDIS_PASSWORD=replaceme
    options:
      disableNameSuffixHash: true

images:
  - name: kgv-api
    newName: acrkgvprod.azurecr.io/kgv-api
    newTag: latest
  - name: kgv-web
    newName: acrkgvprod.azurecr.io/kgv-web
    newTag: latest

replicas:
  - name: api
    count: 2
  - name: web
    count: 2

patches:
  - target:
      kind: Deployment
      name: kgv-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  
  - target:
      kind: Deployment
      name: kgv-web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"