apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgv-api
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: kgv-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgv-web
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: kgv-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgv-postgres
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgv-redis
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgv-backup
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: backup
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kgv-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: kgv-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false