apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kgv-web-hpa
  namespace: kgv-system
  labels:
    app.kubernetes.io/name: kgv-web-hpa
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: kgv-migration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/target: kgv-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kgv-web
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "200"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 3
        periodSeconds: 60
      selectPolicy: Max