apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgv-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "2000m"
            ephemeral-storage: "4Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgv-web
spec:
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"